import { useState } from 'react';
import type { ChangeEvent, JSX, SubmitEvent } from 'react';
import { translations } from '../i18n';
import type { Locale, Translation } from '../i18n';

interface TenantFormData { firstName: string; lastName: string; email: string; cookbookName: string; slug: string; }
export default function AdminTenantCreate({ locale }: { locale: Locale }): JSX.Element {
  const text: Translation = translations[locale]; const [data, setData] = useState<TenantFormData>({ firstName: '', lastName: '', email: '', cookbookName: '', slug: '' }); const [slugChanged, setSlugChanged] = useState<boolean>(false); const [message, setMessage] = useState<string>('');
  function update(name: keyof TenantFormData): (event: ChangeEvent<HTMLInputElement>) => void { return (event: ChangeEvent<HTMLInputElement>): void => { const value: string = event.currentTarget.value; if (name === 'cookbookName') setData({ ...data, cookbookName: value, slug: slugChanged ? data.slug : slugFromCookbookName(value) }); else { if (name === 'slug') setSlugChanged(true); setData({ ...data, [name]: value }); } }; }
  async function submit(event: SubmitEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const response: Response = await fetch('/api/admin/tenants', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); setMessage(response.ok ? text.admin.tenantCreated : text.errors.requestFailed); }
  return <section className="admin-page"><p className="eyebrow">{text.admin.tenants}</p><h1>{text.admin.tenantsNew}</h1><form onSubmit={(event: SubmitEvent<HTMLFormElement>): void => void submit(event)}><label>{text.admin.firstName}<input value={data.firstName} onChange={update('firstName')} required /></label><label>{text.admin.lastName}<input value={data.lastName} onChange={update('lastName')} required /></label><label>{text.login.emailLabel}<input value={data.email} onChange={update('email')} type="email" required /></label><label>{text.admin.cookbookName}<input value={data.cookbookName} onChange={update('cookbookName')} required /></label><label>{text.admin.tenantSlug}<input value={data.slug} onChange={update('slug')} pattern="[a-z0-9]+(-[a-z0-9]+)*" required aria-describedby="tenant-slug-hint" /></label><p className="hint" id="tenant-slug-hint">{text.admin.tenantSlugHint}</p><button type="submit">{text.admin.createTenant}</button></form>{message ? <p className="message" role="status">{message}</p> : null}</section>;
}
function slugFromCookbookName(value: string): string { return value.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); }
